---
sudo: required
language: python
python:
  - "3.6"

before_install:
  - echo "before_install" $PWD
  - "mkdir -p ./../database"
  - "mkdir -p ./../static"
  - "mkdir -p ./../virtualenv"
  - "ls -la ./.."

install:
  - echo "install" $PWD
  - "pip install -r requirements.txt"

script:
  - echo "script" $PWD  
  - "python manage.py collectstatic --noinput"
  - "ls -la ./../database"
  - "python manage.py migrate --noinput"
  - "ls -la ./../static"
   
