---
sudo: required
language: python

before_install:
  - echo "before_install" $PWD

install:
  - echo "install" $PWD

script:
  - echo "script" $PWD
  - mkdir -p ./../{database, static, virtualenv} 
  - "ls -l ./.." 